package contracts

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

type typeInfo struct {
	pyModule string
	pyName   string
	ccHeader string
	ccNS     string
	ccName   string
	goImport string
	goPkg    string
	goName   string
}

type methodInfo struct {
	service      string
	serviceShort string
	method       string
	request      typeInfo
	response     typeInfo
}

func WriteTokens(imagePath, generatedDir, goRuntime string) error {
	data, err := os.ReadFile(imagePath)
	if err != nil {
		return fmt.Errorf("missing descriptor image %s; run mica generate", imagePath)
	}
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, fds); err != nil {
		return fmt.Errorf("invalid descriptor image %s: %w", imagePath, err)
	}
	types := map[string]typeInfo{}
	var methods []methodInfo
	for _, file := range fds.GetFile() {
		pkg := file.GetPackage()
		module := strings.ReplaceAll(strings.TrimSuffix(file.GetName(), ".proto"), "/", ".") + "_pb2"
		header := strings.TrimSuffix(file.GetName(), ".proto") + ".pb.h"
		ccNS := strings.ReplaceAll(pkg, ".", "::")
		goImport, goPkg := splitGoPackage(file.GetOptions().GetGoPackage())
		for _, message := range file.GetMessageType() {
			name := message.GetName()
			types[qualify(pkg, name)] = typeInfo{
				pyModule: module,
				pyName:   name,
				ccHeader: header,
				ccNS:     ccNS,
				ccName:   name,
				goImport: goImport,
				goPkg:    goPkg,
				goName:   name,
			}
		}
		for _, service := range file.GetService() {
			serviceName := qualify(pkg, service.GetName())
			for _, method := range service.GetMethod() {
				request, ok := types[strings.TrimPrefix(method.GetInputType(), ".")]
				if !ok {
					return fmt.Errorf("%s: unknown request type %s", imagePath, method.GetInputType())
				}
				response, ok := types[strings.TrimPrefix(method.GetOutputType(), ".")]
				if !ok {
					return fmt.Errorf("%s: unknown response type %s", imagePath, method.GetOutputType())
				}
				methods = append(methods, methodInfo{
					service:      serviceName,
					serviceShort: service.GetName(),
					method:       method.GetName(),
					request:      request,
					response:     response,
				})
			}
		}
	}
	sort.Slice(methods, func(i, j int) bool {
		if methods[i].service != methods[j].service {
			return methods[i].service < methods[j].service
		}
		return methods[i].method < methods[j].method
	})
	if err := writePythonTokens(generatedDir, methods); err != nil {
		return err
	}
	if err := writeCppTokens(generatedDir, methods); err != nil {
		return err
	}
	if err := writeGoTokens(generatedDir, goRuntime, methods); err != nil {
		return err
	}
	return nil
}

func splitGoPackage(value string) (string, string) {
	if value == "" {
		return "", ""
	}
	if index := strings.Index(value, ";"); index >= 0 {
		return value[:index], value[index+1:]
	}
	parts := strings.Split(value, "/")
	return value, parts[len(parts)-1]
}

func writePythonTokens(generatedDir string, methods []methodInfo) error {
	dest := filepath.Join(generatedDir, "python", "mica_tokens.py")
	if len(methods) == 0 {
		if err := os.Remove(dest); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	imports := map[string]map[string]bool{}
	services := map[string][]methodInfo{}
	var serviceOrder []string
	for _, method := range methods {
		for _, item := range []typeInfo{method.request, method.response} {
			if imports[item.pyModule] == nil {
				imports[item.pyModule] = map[string]bool{}
			}
			imports[item.pyModule][item.pyName] = true
		}
		if _, ok := services[method.serviceShort]; !ok {
			serviceOrder = append(serviceOrder, method.serviceShort)
		}
		services[method.serviceShort] = append(services[method.serviceShort], method)
	}
	sort.Strings(serviceOrder)
	var out strings.Builder
	out.WriteString("# Generated by mica. Do not edit.\n")
	out.WriteString("from mica.method import RpcMethod\n\n")
	for _, module := range sortedKeys(imports) {
		names := sortedKeys(imports[module])
		fmt.Fprintf(&out, "from %s import %s\n", module, strings.Join(names, ", "))
	}
	out.WriteString("\n")
	for _, service := range serviceOrder {
		fmt.Fprintf(&out, "class %s:\n", service)
		for _, method := range services[service] {
			fmt.Fprintf(&out,
				"    %s = RpcMethod(service=%q, method=%q, request_type=%s, response_type=%s)\n",
				method.method, method.service, method.method, method.request.pyName, method.response.pyName)
		}
		out.WriteString("\n")
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, []byte(out.String()), 0o644)
}

func writeCppTokens(generatedDir string, methods []methodInfo) error {
	dest := filepath.Join(generatedDir, "cpp", "mica", "tokens.hpp")
	if len(methods) == 0 {
		if err := os.Remove(dest); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	headers := map[string]bool{}
	for _, method := range methods {
		headers[method.request.ccHeader] = true
		headers[method.response.ccHeader] = true
	}
	var out strings.Builder
	out.WriteString("// Generated by mica. Do not edit.\n")
	out.WriteString("#pragma once\n\n")
	out.WriteString("#include \"mica/method.hpp\"\n")
	for _, header := range sortedKeys(headers) {
		fmt.Fprintf(&out, "#include %q\n", header)
	}
	out.WriteString("\nnamespace mica::tokens {\n\n")
	for _, method := range methods {
		name := method.serviceShort + "_" + method.method
		fmt.Fprintf(&out, "inline const RpcMethod<%s, %s> %s{%q, %q};\n",
			cppType(method.request), cppType(method.response), name, method.service, method.method)
	}
	out.WriteString("\n}  // namespace mica::tokens\n")
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, []byte(out.String()), 0o644)
}

func cppType(info typeInfo) string {
	if info.ccNS == "" {
		return info.ccName
	}
	return info.ccNS + "::" + info.ccName
}

func writeGoTokens(generatedDir, goRuntime string, methods []methodInfo) error {
	dest := filepath.Join(generatedDir, "go", "mica", "tokens", "tokens.go")
	if len(methods) == 0 {
		if err := os.Remove(dest); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	imports := map[string]string{"google.golang.org/protobuf/proto": "", goRuntime: "mica"}
	for _, method := range methods {
		for _, item := range []typeInfo{method.request, method.response} {
			if item.goImport == "" {
				return fmt.Errorf("contract types require a go_package option for the go token generator")
			}
			if _, ok := imports[item.goImport]; !ok {
				imports[item.goImport] = item.goPkg
			}
		}
	}
	var out strings.Builder
	out.WriteString("// Code generated by mica. DO NOT EDIT.\n\n")
	out.WriteString("package tokens\n\nimport (\n")
	for _, path := range sortedKeys(imports) {
		alias := imports[path]
		if alias == "" || alias == filepath.Base(path) {
			fmt.Fprintf(&out, "\t%q\n", path)
		} else {
			fmt.Fprintf(&out, "\t%s %q\n", alias, path)
		}
	}
	out.WriteString(")\n\n")
	for _, method := range methods {
		name := method.serviceShort + method.method
		fmt.Fprintf(&out, "var %s = mica.RPCMethod{\n", name)
		fmt.Fprintf(&out, "\tService: %q,\n", method.service)
		fmt.Fprintf(&out, "\tMethod:  %q,\n", method.method)
		fmt.Fprintf(&out, "\tNewRequest: func() proto.Message { return &%s{} },\n", goType(method.request))
		fmt.Fprintf(&out, "\tNewResponse: func() proto.Message { return &%s{} },\n", goType(method.response))
		out.WriteString("}\n\n")
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return fmt.Errorf("generated go tokens are invalid: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, formatted, 0o644)
}

func goType(info typeInfo) string {
	if info.goPkg == "" {
		return info.goName
	}
	return info.goPkg + "." + info.goName
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
