#!/usr/bin/env python3
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from google.protobuf.descriptor_pb2 import FileDescriptorSet

ROOT = Path(__file__).resolve().parents[1]
IMAGE = ROOT / "generated" / "image.binpb"


def load_methods():
    fds = FileDescriptorSet()
    fds.ParseFromString(IMAGE.read_bytes())
    methods = []
    file_by_type: dict[str, str] = {}
    for fd in fds.file:
        pkg = fd.package
        module = fd.name.replace(".proto", "_pb2").replace("/", ".")
        header = fd.name.replace(".proto", ".pb.h")
        go_import, go_name = _go_package(fd.options.go_package)
        for msg in fd.message_type:
            full = f"{pkg}.{msg.name}" if pkg else msg.name
            file_by_type[full] = {
                "py_module": module,
                "py_name": msg.name,
                "cc_header": header,
                "cc_ns": pkg.replace(".", "::") if pkg else "",
                "cc_name": msg.name,
                "go_import": go_import,
                "go_pkg": go_name,
                "go_name": msg.name,
            }
        for svc in fd.service:
            service = f"{pkg}.{svc.name}" if pkg else svc.name
            for method in svc.method:
                req = method.input_type.lstrip(".")
                resp = method.output_type.lstrip(".")
                methods.append(
                    {
                        "service": service,
                        "service_short": svc.name,
                        "method": method.name,
                        "request": req,
                        "response": resp,
                    }
                )
    return methods, file_by_type


def _go_package(value: str) -> tuple[str, str]:
    if not value:
        return "", ""
    if ";" in value:
        path, name = value.split(";", 1)
        return path, name
    path = value
    name = path.rsplit("/", 1)[-1]
    return path, name


def write_python(methods, types) -> None:
    imports: dict[str, set[str]] = defaultdict(set)
    services: dict[str, list] = defaultdict(list)
    for item in methods:
        req = types[item["request"]]
        resp = types[item["response"]]
        imports[req["py_module"]].add(req["py_name"])
        imports[resp["py_module"]].add(resp["py_name"])
        services[item["service_short"]].append((item, req, resp))
    lines = [
        "# Generated by scripts/generate_tokens.py. Do not edit.",
        "from mica.method import RpcMethod",
        "",
    ]
    for module, names in sorted(imports.items()):
        lines.append(f"from {module} import {', '.join(sorted(names))}")
    lines.append("")
    for service, items in services.items():
        lines.append(f"class {service}:")
        for item, req, resp in items:
            lines.append(
                f"    {item['method']} = RpcMethod("
                f"service={item['service']!r}, method={item['method']!r}, "
                f"request_type={req['py_name']}, response_type={resp['py_name']})"
            )
        lines.append("")
    dest = ROOT / "runtime" / "python" / "src" / "mica" / "_tokens_gen.py"
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_cpp(methods, types) -> None:
    headers = sorted({types[m["request"]]["cc_header"] for m in methods} | {types[m["response"]]["cc_header"] for m in methods})
    lines = [
        "// Generated by scripts/generate_tokens.py. Do not edit.",
        "#pragma once",
        "",
        '#include "mica/method.hpp"',
    ]
    for header in headers:
        lines.append(f'#include "{header}"')
    lines.append("")
    lines.append("namespace mica::tokens {")
    lines.append("")
    for item in methods:
        req = types[item["request"]]
        resp = types[item["response"]]
        req_t = f"{req['cc_ns']}::{req['cc_name']}"
        resp_t = f"{resp['cc_ns']}::{resp['cc_name']}"
        name = f"{item['service_short']}_{item['method']}"
        lines.append(
            f"inline const RpcMethod<{req_t}, {resp_t}> {name}"
            f'{{"{item["service"]}", "{item["method"]}"}};'
        )
    lines.append("")
    lines.append("}  // namespace mica::tokens")
    dest = ROOT / "generated" / "cpp" / "mica" / "tokens.hpp"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_go(methods, types) -> None:
    imports = {"google.golang.org/protobuf/proto", "mica/runtime/go/mica"}
    for item in methods:
        imports.add(types[item["request"]]["go_import"])
        imports.add(types[item["response"]]["go_import"])
    lines = [
        "// Code generated by scripts/generate_tokens.py. DO NOT EDIT.",
        "",
        "package tokens",
        "",
        "import (",
    ]
    for imp in sorted(imports):
        if imp.endswith("/camera/v1"):
            lines.append(f'\tcamerav1 "{imp}"')
        elif imp.endswith("/tracking/v1"):
            lines.append(f'\ttrackingv1 "{imp}"')
        elif imp.endswith("/mica"):
            lines.append(f'\tmica "{imp}"')
        elif imp == "google.golang.org/protobuf/proto":
            lines.append('\t"google.golang.org/protobuf/proto"')
        else:
            lines.append(f'\t"{imp}"')
    lines.append(")")
    lines.append("")
    alias = {}
    for item in methods:
        req = types[item["request"]]
        resp = types[item["response"]]
        req_pkg = _go_alias(req["go_import"])
        resp_pkg = _go_alias(resp["go_import"])
        name = f"{item['service_short']}{item['method']}"
        lines.append(f"var {name} = mica.RPCMethod{{")
        lines.append(f'\tService: "{item["service"]}",')
        lines.append(f'\tMethod:  "{item["method"]}",')
        lines.append(f"\tNewRequest: func() proto.Message {{ return &{req_pkg}.{req['go_name']}{{}} }},")
        lines.append(
            f"\tNewResponse: func() proto.Message {{ return &{resp_pkg}.{resp['go_name']}{{}} }},"
        )
        lines.append("}")
        lines.append("")
        alias[name] = True
    dest = ROOT / "generated" / "go" / "mica" / "tokens" / "tokens.go"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _go_alias(path: str) -> str:
    if path.endswith("/camera/v1"):
        return "camerav1"
    if path.endswith("/tracking/v1"):
        return "trackingv1"
    if path.endswith("/mica/v1"):
        return "micav1"
    return path.rsplit("/", 1)[-1]


def main() -> None:
    methods, types = load_methods()
    write_python(methods, types)
    write_cpp(methods, types)
    write_go(methods, types)


if __name__ == "__main__":
    main()
